---
# RSS Media Bus - Конфигурация источников v3.1 (Обновлено 26.07.2025)
# 
# СТАТИСТИКА ИСТОЧНИКОВ:
# ✅ Активных: 56 (работают стабильно)  
# 🔴 Отключенных: 5 (проблемы с доступом или дубликаты)
# 📊 Всего настроенных: 61 источников
# 
# КАТЕГОРИИ АКТИВНЫХ ИСТОЧНИКОВ:
# • Российские новости: 16 источников (включая rg.ru, стабильные)
# • Международные новости: 9 источников (включая BBC)
# • Экология и климат: 19 источников (включая Verge, обновляются реже)
# • Технологии и IP: 12 источников
#
# Последняя проверка: 26.07.2025 22:25

sources:
  tass.ru:
    url: "https://tass.ru/rss/v2.xml"
    name: "ТАСС - Главные новости"
    active: true
    
  ria.ru:
    url: "https://ria.ru/export/rss2/archive/index.xml"
    name: "РИА Новости"
    active: true
    
  rbc.ru:
    url: "http://static.feed.rbc.ru/rbc/logical/footer/news.rss"
    name: "РБК"
    active: true
    


  techcrunch.com:
    url: "https://techcrunch.com/category/climate/feed/"
    name: "TechCrunch Climate"
    active: true
    # Проблема: нет новых статей 56+ часов (проверено 26.07.2025)

  lenta.ru:
    url: "https://lenta.ru/rss"
    name: "Лента.ру"
    active: true
    
  interfax.ru:
    url: "https://www.interfax.ru/rss.asp"
    name: "Интерфакс"
    active: true
    
    vedomosti.ru:
    url: "https://vedomosti.ru/rss/articles"
    name: "Ведомости - Статьи"
    active: true
    
  vedomosti_news.ru:
    url: "https://vedomosti.ru/rss/news"
    name: "Ведомости - Новости"
    active: true
    
  vedomosti_issue.ru:
    url: "https://vedomosti.ru/rss/issue"
    name: "Ведомости - Выпуски"
    active: true
    
  rbc_full.ru:
    url: "https://rssexport.rbc.ru/rbcnews/news/30/full.rss"
    name: "РБК - Полные новости"
    active: true
      

  mk.ru:
    url: "https://www.mk.ru/rss/index.xml"
    name: "Московский комсомолец"
    active: true
    

  rt.com:
    url: "https://russian.rt.com/rss"
    name: "RT на русском"
    active: true
    
  life.ru:
    url: "https://life.ru/xml/feed.xml"
    name: "Life.ru"
    active: true
    
  aif.ru:
    url: "https://aif.ru/rss/all.php"
    name: "Аргументы и факты"
    active: true
    
  360.ru:
    url: "https://360.ru/rss/"
    name: "360.ru"
    active: true
    
  pnp.ru:
    url: "https://www.pnp.ru/rss/index.xml"
    name: "Парламентская газета"
    active: true
    
  ura.news:
    url: "https://ura.news/rss"
    name: "URA.news"
    active: true
    
  iz.ru:
    url: "https://iz.ru/xml/rss/all.xml"
    name: "Известия"
    active: true

  pv-magazine.com:
    url: "https://www.pv-magazine.com/feed/"
    name: "PV Magazine"
    active: true
    
  ecopravda.ru:
    url: "https://www.ecopravda.ru/feed/"
    name: "Эко Правда"
    active: true
    
  electrive.com:
    url: "https://www.electrive.com/feed/"
    name: "Electrive"
    active: true
    

  electrek.co:
    url: "https://electrek.co/feed/"
    name: "Electrek"
    active: true
    
  bloomberg_green.com:
    url: "https://feeds.bloomberg.com/green/news.rss"
    name: "Bloomberg Green"
    active: true
    
  bloomberg_esg.com:
    url: "https://news.bloomberglaw.com/rss/esg"
    name: "Bloomberg ESG"
    active: true
    proxy_required: true
    proxy_settings:
      type: "http"
      url: "http://vExvSw:wShhT3@190.111.161.234:9372"
      region: "usa"
    
  mit_climate.edu:
    url: "https://news.mit.edu/rss/topic/climate-change-and-sustainability"
    name: "MIT Climate News"
    active: true
    
  scitechdaily.com:
    url: "https://scitechdaily.com/news/earth/feed/"
    name: "SciTechDaily Earth"
    active: true
    
  esgtoday.com:
    url: "https://www.esgtoday.com/feed/"
    name: "ESG Today"
    active: true
    
  esgnews.com:
    url: "https://esgnews.com/feed/"
    name: "ESG News"
    active: true
    
  nytimes_environment.com:
    url: "https://www.nytimes.com/services/xml/rss/nyt/Environment.xml"
    name: "NY Times Environment"
    active: true
    
  grist.org:
    url: "https://grist.org/feed/"
    name: "Grist Climate"
    active: true
    
  guardian_environment.com:
    url: "https://www.theguardian.com/environment/rss"
    name: "Guardian Environment"
    active: true
    
  nature_climate.com:
    url: "https://www.nature.com/nclimate.rss"
    name: "Nature Climate Change"
    active: true
    
  eco-business.com:
    url: "https://www.eco-business.com/feeds/all/"
    name: "Eco Business"
    active: true
    
  eu-startups.com:
    url: "https://www.eu-startups.com/feed/"
    name: "EU Startups"
    active: true
    
  ecowatch.com:
    url: "https://www.ecowatch.com/rss"
    name: "EcoWatch"
    active: true
    
  happyeconews.com:
    url: "https://happyeconews.com/feed/"
    name: "Happy Eco News"
    active: true
    
  mongabay.com:
    url: "https://news.mongabay.com/feed/"
    name: "Mongabay"
    active: true
    
  sustainablebrands.com:
    url: "https://sustainablebrands.com/rss"
    name: "Sustainable Brands"
    active: true
    
  # techcrunch_climate.com - удален как дубликат
  # Используется только techcrunch.com для обоих ботов (контент пересекается)
    
  verge_climate.com:
    url: "https://www.theverge.com/rss/climate-change/index.xml"
    name: "The Verge Climate"
    active: true
    # RSS работает, иногда просто нет климатических новостей

  worldtrademarkreview.com:
    url: "https://www.worldtrademarkreview.com/rss"
    name: "World Trademark Review"
    active: true

  chatgptiseatingtheworld.com:
    url: "https://chatgptiseatingtheworld.com/feed/"
    name: "ChatGPT is Eating the World"
    active: true

  wipo.int:
    url: "https://www.wipo.int/portal/en/rss.xml"
    name: "WIPO - World Intellectual Property Organization"
    active: true

  torrentfreak.com:
    url: "https://torrentfreak.com/feed"
    name: "TorrentFreak"
    active: true

  bloomberg_ip.com:
    url: "https://news.bloomberglaw.com/rss/ip-law"
    name: "Bloomberg Law - IP Law"
    active: true
    proxy_required: true
    proxy_settings:
      type: "http"
      url: "http://vExvSw:wShhT3@190.111.161.234:9372"
      region: "usa"

  uspto.gov:
    url: "https://www.uspto.gov/rss.xml"
    name: "USPTO - US Patent and Trademark Office"
    active: true

  rapsinews.ru:
    url: "http://rapsinews.ru/export/rss2/index.xml"
    name: "РАПСИ Новости"
    active: true

  copyrightlately.com:
    url: "https://copyrightlately.com/rss"
    name: "Copyright Lately"
    active: true

  copyright_case_act.gov:
    url: "https://www.copyright.gov/rss/case_act.xml"
    name: "US Copyright - Case Act"
    active: true

  copyright_creativity.gov:
    url: "https://www.copyright.gov/rss/creativity.xml"
    name: "US Copyright - Creativity"
    active: true

  copyright_eservice.gov:
    url: "https://www.copyright.gov/rss/eservice.xml"
    name: "US Copyright - eService"
    active: true

  copyright_legislation.gov:
    url: "https://www.copyright.gov/rss/legislation.xml"
    name: "US Copyright - Legislation"
    active: true

  copyright_events.gov:
    url: "https://www.copyright.gov/rss/events.xml"
    name: "US Copyright - Events"
    active: true

  euronews_green.ru:
    url: "https://ru.euronews.com/rss?format=mrss&level=vertical&name=green"
    name: "Euronews Green (РУ)"
    active: true
    proxy_required: true
    proxy_settings:
      type: "http"
      url: "http://vExvSw:wShhT3@190.111.161.234:9372"
      region: "europe"

  bbc.co.uk:
    url: "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml"
    name: "BBC Science & Environment"
    active: true
    proxy_required: true
    proxy_settings:
      type: "http"
      url: "http://vExvSw:wShhT3@190.111.161.234:9372"
      region: "europe"
    # RSS работает с прокси, редко публикует статьи

  ecopolitic.com.ua:
    url: "https://ecopolitic.com.ua/ua/category/global_green_ua/feed/"
    name: "Эко Политика - Глобальная зелёная"
    active: true
    proxy_required: true
    proxy_settings:
      type: "http"
      url: "http://vExvSw:wShhT3@190.111.161.234:9372"
      region: "ukraine"

  renewableenergyworld.com:
    url: "https://www.renewableenergyworld.com/feed/"
    name: "Renewable Energy World"
    active: true
    proxy_required: true
    proxy_settings:
      type: "http"
      url: "http://vExvSw:wShhT3@190.111.161.234:9372"
      region: "usa"

  rg.ru:
    url: "https://rg.ru/xml/index.xml"
    name: "Российская газета"
    active: true
    # RSS РАБОТАЕТ! Проблема была в нашем тестировании (26.07.2025)
    # Содержит свежие новости, обновляется регулярно
  #   problem: "RSS URL возвращает 404"

# ========================================
# ПРОБЛЕМНЫЕ ИСТОЧНИКИ (отключены)
# Требуют исправления или поиска альтернатив
# ========================================

  # gazeta.ru:
  #   url: "https://www.gazeta.ru/"  # НЕ RSS URL! Нужно найти правильный RSS
  #   name: "Газета.ру"
  #   active: false
  #   problem: "Указан URL главной страницы вместо RSS"
  
  # reuters.com:
  #   url: "https://www.reuters.com/pf/api/v3/content/fetch/articles-by-section-alias-or-id-v1?query=%7B%22arc-site%22%3A%22reuters%22%2C%22called_from_a_component%22%3Atrue%2C%22fetch_type%22%3A%22collection%22%2C%22section_id%22%3A%22%2Fsustainability%2F%22%2C%22size%22%3A20%7D"
  #   name: "Reuters Sustainability"
  #   active: false
  #   problem: "API endpoint не отвечает"

  # kp.ru:
  #   url: "https://www.kp.ru/rss/allsections.xml"
  #   name: "Комсомольская правда"
  #   active: false
  #   problem: "RSS не отвечает"

  # ✅ ИСПРАВЛЕННЫЕ ПРОБЛЕМЫ (26.07.2025):
  # • techcrunch_climate.com - удален как дубликат
  # • verge_climate.com - исправлен URL на HTTPS  
  # • bbc.co.uk - добавлен прокси для доступа
  # • rg.ru - восстановлен (проблема была в тестировании)  


