---
# RSS Media Bus - Конфигурация пользователей v3.0

users:
  test_user:
    name: "Test Monitor"
    description: "Тестовый пользователь для отладки системы"
    active: true
    
    # Telegram настройки (ЗАПОЛНИТЬ ДЛЯ ТЕСТИРОВАНИЯ)
    telegram:
      chat_id: ""                    # Заполнить свой chat_id
      bot_token: ""                  # Заполнить токен бота
      topic_id: null
      enabled: false                 # Включить после заполнения токенов
    
    # Источники для мониторинга
    sources:
      - tass_main
      - ria_main
      - rbc_main
    
    # Цепочка обработки
    processors:
      - name: "keyword_filter"
        config:
          keywords: 
            - "тест"
            - "новости"
            - "важно"
          mode: "include"
          min_matches: 1
          
      - name: "telegram_sender"
        config:
          format: "markdown"
          include_source: true
          max_preview_length: 200

  # === АВТОМАТИЧЕСКИ ЗАРЕГИСТРИРОВАННЫЕ ПОЛЬЗОВАТЕЛИ ===
  
  yrcnw_user:
    name: "И Monitor"
    description: "Автоматически зарегистрированный пользователь через бота"
    active: true
    registration_method: "telegram_bot"
    telegram_id: 2337404
    username: "yrcnw"
    first_name: "И"
    created_at: "2025-07-19T15:12:54.358072"
    
    # Telegram настройки
    telegram:
      chat_id: "2337404"
      bot_token: ""                  # Заполнить через /set_token
      topic_id: null
      enabled: false                 # Включить после настройки токена
    
    # Источники для мониторинга (базовый набор)
    sources:
      - tass_main
      - ria_main
    
    # Цепочка обработки (базовая)
    processors:
      - name: "telegram_sender"
        config:
          format: "markdown"
          include_source: true
          max_preview_length: 200

# === ШАБЛОНЫ ДЛЯ АВТОСОЗДАНИЯ ПОЛЬЗОВАТЕЛЕЙ ===
user_templates:
  basic_news:
    name: "Базовые новости"
    description: "Простая новостная лента без фильтров"
    telegram:
      enabled: true
    sources:
      - tass_main
      - ria_main
    processors:
      - name: "telegram_sender"
        config:
          format: "markdown"
          
  filtered_news:
    name: "Фильтрованные новости"
    description: "Новости с фильтрацией по ключевым словам"
    telegram:
      enabled: true
    sources:
      - tass_main
      - ria_main
      - rbc_main
    processors:
      - name: "keyword_filter"
        config:
          keywords: []  # Пользователь задаст сам
          mode: "include"
      - name: "telegram_sender"
        config:
          format: "markdown"
          
  international:
    name: "Международные новости"
    description: "Международные источники с переводом"
    telegram:
      enabled: true
    sources:
      - reuters_sustainability
      - bbc_science
      - techcrunch_climate
    processors:
      - name: "translator"
        config:
          target_language: "ru"
      - name: "telegram_sender"
        config:
          format: "markdown" 