smm_gov_redaktor:
  active: true
  telegram_configs:
    main_all_sources:
      enabled: true
      bot_token: "7000553711:AAGa4WKSGJGheJcydtR9V0L9vnxlK89Twgo"
      chat_id: -1002883915655
      topics_mapping:
        360.ru: 19667
        aif.ru: 19665
        bbc.co.uk: 19637
        bbc_science.co.uk: 19701
        bloomberg_esg.com: 19691
        bloomberg_green.com: 19689
        eco-business.com: 19711
        ecopolitic.com.ua: 19677
        ecopravda.ru: 19681
        ecowatch.com: 19715
        electrek.co: 19687
        electrive.com: 19683
        esgnews.com: 19699
        esgtoday.com: 19697
        eu-startups.com: 19713
        euronews_green.ru: 19679
        gazeta.ru: 19653
        grist.org: 19705
        guardian_environment.com: 19707
        happyeconews.com: 19717
        interfax.ru: 19643
        iz.ru: 19673
        kp.ru: 19659
        lenta.ru: 19641
        life.ru: 19663
        mit_climate.edu: 19693
        mk.ru: 19657
        mongabay.com: 19719
        nature_climate.com: 19709
        nytimes_environment.com: 19703
        pnp.ru: 19669
        pv-magazine.com: 19675
        rbc.ru: 19633
        rbc_full.ru: 19651
        renewableenergyworld.com: 19685
        reuters.com: 19635
        rg.ru: 19655
        ria.ru: 19631
        rt.com: 19661
        scitechdaily.com: 19695
        sustainablebrands.com: 19721
        tass.ru: 19629
        techcrunch.com: 19639
        techcrunch_climate.com: 19723
        ura.news: 19671
        vedomosti.ru: 19645
        vedomosti_issue.ru: 19649
        vedomosti_news.ru: 19647
        verge_climate.com: 19725
